server:
  port: 1101

spring:
  application:
    #   feign不支持下划线"_"，支持"-"
    name: feign-service-b

feign:
  hystrix:
    enabled: true

eureka:
  client:
    #    可用区域映射到与eureka服务器通信的完全限定URL列表。每个值可以是单个URL或逗号分隔的备用位置列表。
    serviceUrl:
      defaultZone: http://server1:1000/eureka/,http://server2:1001/eureka/
      #   询问Eureka服务url信息变化的时间间隔（s），默认为300秒
      pollIntervalSeconds: 1800
    #    用于指示Eureka客户端已启用的标志，默认true
    enabled: true
    healthcheck:
      enabled: true
    fetch-registry: true
#    #    指示此实例是否应将其信息注册到eureka服务器以供其他服务发现，默认为false
#    register-with-eureka: true
#    #    最初复制实例信息到eureka服务器所需的时间（s），默认为40秒
#    initial-instance-info-replication-interval-seconds: 10
#    #    复制实例变化信息到eureka服务器所需要的时间间隔（s），默认为30秒
#    instance-info-replication-interval-seconds: 10
#    #    从eureka服务器注册表中获取注册信息的时间间隔（s），默认为30秒
#    registry-fetch-interval-seconds: 10
#    #    询问Eureka Server信息变化的时间间隔（s），默认为300秒
#    eureka-service-url-poll-interval-seconds: 60
#    #    读取Eureka Server 超时时间（s），默认8秒
#    eureka-server-read-timeout-seconds: 10
#    #    连接Eureka Server 超时时间（s），默认5秒
#    eureka-server-connect-timeout-seconds: 10
#    #    获取从eureka客户端到所有eureka服务器的连接总数,默认200个
#    eureka-server-total-connections: 200
#    #    获取从eureka客户端到eureka服务器主机允许的连接总数，默认50个
#    eureka-server-total-connections-per-host: 50
#    #    连接到 Eureka Server 空闲连接的超时时间（s），默认30
#    eureka-connection-idle-timeout-seconds: 30
#    #    指示客户端是否仅对单个VIP的注册表信息感兴趣，默认为null
#    registry-refresh-single-vip-address: null
#    #    心跳保持线程池初始化线程数，默认2个
#    heartbeat-executor-thread-pool-size: 2
#    #    心跳超时重试延迟时间的最大乘数值，默认10
#    heartbeat-executor-exponential-back-off-bound: 10
#    #    指示eureka客户端是否应使用DNS机制来获取要与之通信的eureka服务器列表。当DNS名称更新为具有其他服务器时，eureka客户端轮询eurekaServiceUrlPollIntervalSeconds中指定的信息后立即使用该信息。
#    use-dns-for-fetching-service-urls: false
#    #    实例是否使用同一zone里的eureka服务器，默认为true，理想状态下，eureka客户端与服务端是在同一zone下
#    prefer-same-zone-eureka: true
#    #    是否记录eureka服务器和客户端之间在注册表的信息方面的差异，默认为false
#    log-delta-diff: true
#    #    指示eureka客户端是否禁用增量提取，默认false
#    disable-delta: false
##      client-data-accept
#      #      获取此实例所在区域的可用区域列表（在AWS数据中心中使用）。更改在运行时在registryFetchIntervalSeconds指定的下一个注册表获取周期生效。
#      #      availability-zones.*:
#    #    逗号分隔的区域列表，提取eureka注册表信息
#    #    fetch-remote-regions-registry:
#    #   客户端的状态更新到远程服务器上，默认为true
#    on-demand-update-status-change: true
#    #    指示服务器是否可以将客户端请求重定向到备份服务器/集群。如果设置为false，则服务器将直接处理请求。如果设置为true，则可以将HTTP重定向发送到具有新服务器位置的客户端。
#    allow-redirects: false
#    #    impl
#    #
#    #获取实现BackupRegistry的实现的名称，该实现仅在eureka客户端启动时第一次作为后备选项获取注册表信息。 对于需要额外的注册表信息弹性的应用程序，可能需要这样做，否则它将无法运行。
#    #    backup-registry-impl:
#    #    在发生一系列超时的情况下，它是重试延迟的最大乘数值，默认10
#    cache-refresh-executor-exponential-back-off-bound: 10
##    缓存刷新线程池初始化线程数量，默认2
#    cache-refresh-executor-thread-pool-size: 1






management:
  endpoint:
    hystrix:
      stream:
        enabled: true
      config:



